# Generated by Django 5.2.7 on 2025-12-31 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_sparqlendpointconfiguration_engine'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompareGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField()),
                ('endpoints', models.ManyToManyField(to='api.sparqlendpointconfiguration')),
            ],
        ),
    ]
