# Generated by Django 5.2.7 on 2026-01-16 18:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0006_alter_sparqlendpointconfiguration_engine"),
    ]

    operations = [
        migrations.AddField(
            model_name="sparqlendpointconfiguration",
            name="hover",
            field=models.TextField(
                blank=True,
                default="",
                help_text="The query for fetching hover information for IRIs",
                verbose_name="Hover",
            ),
        ),
    ]
