# Generated by Django 5.2.7 on 2026-02-12 02:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0008_sparqlendpointconfiguration_map_view_url"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sparqlendpointconfiguration",
            name="prefixes",
            field=models.TextField(
                blank=True,
                default="",
                help_text="A list of prefixes that should be suggested. Use this notation: @prefix schema: &lt;https://www.schema.org/&gt; .",
                verbose_name="Suggested Prefixes",
            ),
        ),
    ]
