# Generated by Django 5.2.7 on 2026-02-23 13:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "api",
            "0010_sparqlendpointconfiguration_values_completion_context_insensitive_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="sparqlendpointconfiguration",
            name="hover",
            field=models.TextField(
                blank=True,
                default='    # Inherit PREFIX declarations from the editor document and configuration\n    {% include "prefix_declarations" %}\n    PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>\n\n    # {{ entity }} is the IRI currently under the cursor\n    # Both fields are OPTIONAL so the tooltip still renders if only one is present\n    SELECT ?qlue_ls_label ?qlue_ls_alias WHERE {\n      # Fetch human-readable label; prefer English, allow untagged fallback\n      OPTIONAL {\n        {{ entity }} rdfs:label ?qlue_ls_label .\n        FILTER(LANG(?qlue_ls_label) = "en" || LANG(?qlue_ls_label) = "")\n      }\n      # Fetch description shown as secondary detail in the tooltip\n      OPTIONAL {\n        {{ entity }} rdfs:comment ?qlue_ls_alias .\n        FILTER(LANG(?qlue_ls_alias) = "en" || LANG(?qlue_ls_alias) = "")\n      }\n    }\n    LIMIT 1\n    ',
                help_text="The query for fetching hover information for IRIs",
                verbose_name="Hover",
            ),
        ),
        migrations.AlterField(
            model_name="sparqlendpointconfiguration",
            name="object_completion_context_insensitive",
            field=models.TextField(
                blank=True,
                default='    # Inherit PREFIX declarations from the editor document and configuration\n    {% include "prefix_declarations" %}\n    PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>\n    \n    SELECT ?qlue_ls_entity ?qlue_ls_label ?qlue_ls_alias ?qlue_ls_count WHERE {\n      {\n        # Inner query: scan all object positions, restrict to IRIs to avoid surfacing\n        # raw string/numeric literals as completion candidates\n        SELECT ?qlue_ls_entity (COUNT(*) AS ?qlue_ls_count) WHERE {\n          ?s ?p ?qlue_ls_entity .\n          FILTER(isIRI(?qlue_ls_entity))\n        }\n        GROUP BY ?qlue_ls_entity\n        ORDER BY DESC(?qlue_ls_count)\n        LIMIT {{ limit }}\n        OFFSET {{ offset }}\n      }\n      # Fetch human-readable label for display; prefer English, allow untagged fallback\n      OPTIONAL {\n        ?qlue_ls_entity rdfs:label ?qlue_ls_label .\n        FILTER(LANG(?qlue_ls_label) = "en" || LANG(?qlue_ls_label) = "")\n      }\n      # Fetch description for the completion item detail line\n      OPTIONAL {\n        ?qlue_ls_entity rdfs:comment ?qlue_ls_alias .\n        FILTER(LANG(?qlue_ls_alias) = "en" || LANG(?qlue_ls_alias) = "")\n      }\n      {% if search_term_uncompressed %}\n      # User typed a prefixed IRI — match against the expanded IRI string\n      FILTER(STRSTARTS(STR(?qlue_ls_entity), "^{{ search_term_uncompressed }}"))\n      {% elif search_term %}\n      # User typed plain text — match against label or description;\n      # applied in the outer query so it can reference the fetched label/alias variables\n      FILTER(\n        REGEX(STR(?qlue_ls_label), "^{{ search_term }}", "i")\n        || REGEX(STR(?qlue_ls_alias), "^{{ search_term }}", "i")\n      )\n      {% endif %}\n    }',
                help_text="The query for <em>context-insensitive</em> object autocompletion",
                verbose_name="Object completion (context insensitive)",
            ),
        ),
        migrations.AlterField(
            model_name="sparqlendpointconfiguration",
            name="object_completion_context_sensitive",
            field=models.TextField(
                blank=True,
                default='    # Inherit PREFIX declarations from the editor document and configuration\n    {% include "prefix_declarations" %}\n    PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>\n    \n    SELECT ?qlue_ls_entity ?qlue_ls_label ?qlue_ls_alias ?qlue_ls_count WHERE {\n      {\n        # Inner query: use surrounding context + local triple pattern to narrow\n        # candidate objects to those consistent with the known predicate/subject\n        SELECT ?qlue_ls_entity (COUNT(*) AS ?qlue_ls_count) WHERE {\n          {{ context }}\n          {{ local_context }}\n        }\n        GROUP BY ?qlue_ls_entity\n        ORDER BY DESC(?qlue_ls_count)\n        LIMIT {{ limit }}\n        OFFSET {{ offset }}\n      }\n      # Fetch human-readable label for display; prefer English, allow untagged fallback\n      OPTIONAL {\n        ?qlue_ls_entity rdfs:label ?qlue_ls_label .\n        FILTER(LANG(?qlue_ls_label) = "en" || LANG(?qlue_ls_label) = "")\n      }\n      # Fetch description for the completion item detail line\n      OPTIONAL {\n        ?qlue_ls_entity rdfs:comment ?qlue_ls_alias .\n        FILTER(LANG(?qlue_ls_alias) = "en" || LANG(?qlue_ls_alias) = "")\n      }\n      {% if search_term_uncompressed %}\n      # User typed a prefixed IRI — match against the expanded IRI string\n      FILTER(STRSTARTS(STR(?qlue_ls_entity), "^{{ search_term_uncompressed }}"))\n      {% elif search_term %}\n      # User typed plain text — match against label or description;\n      # applied in the outer query so it can reference the fetched label/alias variables\n      FILTER(\n        REGEX(STR(?qlue_ls_label), "^{{ search_term }}", "i")\n        || REGEX(STR(?qlue_ls_alias), "^{{ search_term }}", "i")\n      )\n      {% endif %}\n    }',
                help_text="The query for <em>context-sensitive</em> object autocompletion",
                verbose_name="Object completion (context sensitive)",
            ),
        ),
        migrations.AlterField(
            model_name="sparqlendpointconfiguration",
            name="predicate_completion_context_insensitive",
            field=models.TextField(
                blank=True,
                default='    # Inherit PREFIX declarations from the editor document and configuration\n    {% include "prefix_declarations" %}\n    PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>\n    \n    SELECT ?qlue_ls_entity ?qlue_ls_label ?qlue_ls_alias ?qlue_ls_count WHERE {\n      {\n        # Inner query: scan all triples and rank predicates by usage frequency\n        SELECT ?qlue_ls_entity (COUNT(*) AS ?qlue_ls_count) WHERE {\n          ?s ?qlue_ls_entity ?o .\n          {% if search_term_uncompressed %}\n          # User typed a prefixed IRI (e.g. rdf:type) — match against the expanded IRI string\n          FILTER(STRSTARTS(STR(?qlue_ls_entity), "^{{ search_term_uncompressed }}"))\n          {% elif search_term %}\n          # User typed a plain text term — match against the predicate\'s label;\n          # accept English labels and untagged literals so language-free graphs still work\n          ?qlue_ls_entity rdfs:label ?searchLabel .\n          FILTER(LANG(?searchLabel) = "en" || LANG(?searchLabel) = "")\n          FILTER(REGEX(STR(?searchLabel), "^{{ search_term }}", "i"))\n          {% endif %}\n        }\n        GROUP BY ?qlue_ls_entity\n        ORDER BY DESC(?qlue_ls_count)\n        LIMIT {{ limit }}\n        OFFSET {{ offset }}\n      }\n      # Fetch human-readable label for display; prefer English, allow untagged fallback\n      OPTIONAL {\n        ?qlue_ls_entity rdfs:label ?qlue_ls_label .\n        FILTER(LANG(?qlue_ls_label) = "en" || LANG(?qlue_ls_label) = "")\n      }\n      # Fetch description for the completion item detail line\n      OPTIONAL {\n        ?qlue_ls_entity rdfs:comment ?qlue_ls_alias .\n        FILTER(LANG(?qlue_ls_alias) = "en" || LANG(?qlue_ls_alias) = "")\n      }\n    }',
                help_text="The query for <em>context-insensitive</em> predicate autocompletion",
                verbose_name="Predicate completion (context insensitive)",
            ),
        ),
        migrations.AlterField(
            model_name="sparqlendpointconfiguration",
            name="predicate_completion_context_sensitive",
            field=models.TextField(
                blank=True,
                default='    # Inherit PREFIX declarations from the editor document and configuration\n    {% include "prefix_declarations" %}\n    PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>\n    \n    SELECT ?qlue_ls_entity ?qlue_ls_label ?qlue_ls_alias ?qlue_ls_count WHERE {\n      {\n        # Inner query: use surrounding context + local triple pattern to find\n        # predicates actually used in this subject\'s neighbourhood\n        SELECT ?qlue_ls_entity (COUNT(*) AS ?qlue_ls_count) WHERE {\n          {{ context }}\n          {{ local_context }}\n          {% if search_term_uncompressed %}\n          # User typed a prefixed IRI (e.g. rdf:type) — match against the expanded IRI string\n          FILTER(STRSTARTS(STR(?qlue_ls_entity), "^{{ search_term_uncompressed }}"))\n          {% elif search_term %}\n          # User typed a plain text term — match against the predicate\'s label;\n          # accept English labels and untagged literals so language-free graphs still work\n          ?qlue_ls_entity rdfs:label ?searchLabel .\n          FILTER(LANG(?searchLabel) = "en" || LANG(?searchLabel) = "")\n          FILTER(REGEX(STR(?searchLabel), "^{ search_term }}", "i"))\n          {% endif %}\n        }\n        GROUP BY ?qlue_ls_entity\n        ORDER BY DESC(?qlue_ls_count)\n        LIMIT {{ limit }}\n        OFFSET {{ offset }}\n      }\n      # Fetch human-readable label for display; prefer English, allow untagged fallback\n      OPTIONAL {\n        ?qlue_ls_entity rdfs:label ?qlue_ls_label .\n        FILTER(LANG(?qlue_ls_label) = "en" || LANG(?qlue_ls_label) = "")\n      }\n      # Fetch description for the completion item detail line\n      OPTIONAL {\n        ?qlue_ls_entity rdfs:comment ?qlue_ls_alias .\n        FILTER(LANG(?qlue_ls_alias) = "en" || LANG(?qlue_ls_alias) = "")\n      }\n    }',
                help_text="The query for <em>context-sensitive</em> predicate autocompletion",
                verbose_name="Predicate completion (context sensitive)",
            ),
        ),
        migrations.AlterField(
            model_name="sparqlendpointconfiguration",
            name="prefixes",
            field=models.TextField(
                blank=True,
                default="PREFIX owl: <http://www.w3.org/2002/07/owl#>\nPREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>\nPREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>\nPREFIX schema: <http://schema.org/>\nPREFIX skos: <http://www.w3.org/2004/02/skos/core#>\nPREFIX xsd: <http://www.w3.org/2001/XMLSchema#>\nPREFIX foaf: <http://xmlns.com/foaf/0.1/>",
                help_text="A list of prefixes that should be suggested. Use this notation: PREFIX schema: &lt;https://www.schema.org/&gt;",
                verbose_name="Suggested Prefixes",
            ),
        ),
        migrations.AlterField(
            model_name="sparqlendpointconfiguration",
            name="subject_completion",
            field=models.TextField(
                blank=True,
                default='    PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>\n\n    SELECT ?qlue_ls_entity ?qlue_ls_label ?qlue_ls_alias ?qlue_ls_count WHERE {\n      {\n        SELECT ?qlue_ls_entity (COUNT(*) AS ?qlue_ls_count) WHERE {\n          ?qlue_ls_entity ?p ?o .\n          {% if search_term %}\n          ?qlue_ls_entity rdfs:label ?searchLabel .\n          FILTER(LANG(?searchLabel) = "en" || LANG(?searchLabel) = "")\n          FILTER(REGEX(STR(?searchLabel), "^{{ search_term }}", "i"))\n          {% endif %}\n        }\n        GROUP BY ?qlue_ls_entity\n        ORDER BY DESC(?qlue_ls_count)\n        LIMIT {{ limit }}\n        OFFSET {{ offset }}\n      }\n      OPTIONAL {\n        ?qlue_ls_entity rdfs:label ?qlue_ls_label .\n        FILTER(LANG(?qlue_ls_label) = "en" || LANG(?qlue_ls_label) = "")\n      }\n      OPTIONAL {\n        ?qlue_ls_entity rdfs:comment ?qlue_ls_alias .\n        FILTER(LANG(?qlue_ls_alias) = "en" || LANG(?qlue_ls_alias) = "")\n      }\n    }',
                help_text="The query for subject autocompletion.",
                verbose_name="Subject completion",
            ),
        ),
        migrations.AlterField(
            model_name="sparqlendpointconfiguration",
            name="values_completion_context_insensitive",
            field=models.TextField(
                blank=True,
                default='    # Inherit PREFIX declarations from the editor document and configuration\n    {% include "prefix_declarations" %}\n    PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>\n\n    SELECT ?qlue_ls_entity ?qlue_ls_label ?qlue_ls_alias ?qlue_ls_count WHERE {\n      {\n        # Inner query: local_context is a BIND(?var AS ?qlue_ls_entity) expression;\n        # no surrounding context available, so rank by general occurrence count\n        SELECT ?qlue_ls_entity (COUNT(*) AS ?qlue_ls_count) WHERE {\n          {{ local_context }}\n          ?qlue_ls_entity ?p ?o .\n        }\n        GROUP BY ?qlue_ls_entity\n        ORDER BY DESC(?qlue_ls_count)\n        LIMIT {{ limit }}\n        OFFSET {{ offset }}\n      }\n      # Fetch human-readable label for display; prefer English, allow untagged fallback\n      OPTIONAL {\n        ?qlue_ls_entity rdfs:label ?qlue_ls_label .\n        FILTER(LANG(?qlue_ls_label) = "en" || LANG(?qlue_ls_label) = "")\n      }\n      # Fetch description for the completion item detail line\n      OPTIONAL {\n        ?qlue_ls_entity rdfs:comment ?qlue_ls_alias .\n        FILTER(LANG(?qlue_ls_alias) = "en" || LANG(?qlue_ls_alias) = "")\n      }\n      {% if search_term_uncompressed %}\n      # User typed a prefixed IRI — match against the expanded IRI string\n      FILTER(STRSTARTS(STR(?qlue_ls_entity), "^{{ search_term_uncompressed }}"))\n      {% elif search_term %}\n      # User typed plain text — match against label or description;\n      # applied in the outer query so it can reference the fetched label/alias variables\n      FILTER(\n        REGEX(STR(?qlue_ls_label), "^{{ search_term }}", "i")\n        || REGEX(STR(?qlue_ls_alias), "^{{ search_term }}", "i")\n      )\n      {% endif %}\n    }',
                help_text="The query for <em>context-insensitive</em> values autocompletion",
                verbose_name="Values completion (context insensitive)",
            ),
        ),
        migrations.AlterField(
            model_name="sparqlendpointconfiguration",
            name="values_completion_context_sensitive",
            field=models.TextField(
                blank=True,
                default='    # Inherit PREFIX declarations from the editor document and configuration\n    {% include "prefix_declarations" %}\n    PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>\n\n    SELECT ?qlue_ls_entity ?qlue_ls_label ?qlue_ls_alias ?qlue_ls_count WHERE {\n      {\n        # Inner query: local_context is a BIND(?var AS ?qlue_ls_entity) expression;\n        # context contains the connected triple patterns that constrain valid values\n        SELECT ?qlue_ls_entity (COUNT(*) AS ?qlue_ls_count) WHERE {\n          {{ context }}\n          {{ local_context }}\n        }\n        GROUP BY ?qlue_ls_entity\n        ORDER BY DESC(?qlue_ls_count)\n        LIMIT {{ limit }}\n        OFFSET {{ offset }}\n      }\n      # Fetch human-readable label for display; prefer English, allow untagged fallback\n      OPTIONAL {\n        ?qlue_ls_entity rdfs:label ?qlue_ls_label .\n        FILTER(LANG(?qlue_ls_label) = "en" || LANG(?qlue_ls_label) = "")\n      }\n      # Fetch description for the completion item detail line\n      OPTIONAL {\n        ?qlue_ls_entity rdfs:comment ?qlue_ls_alias .\n        FILTER(LANG(?qlue_ls_alias) = "en" || LANG(?qlue_ls_alias) = "")\n      }\n      {% if search_term_uncompressed %}\n      # User typed a prefixed IRI — match against the expanded IRI string\n      FILTER(STRSTARTS(STR(?qlue_ls_entity), "^{{ search_term_uncompressed }}"))\n      {% elif search_term %}\n      # User typed plain text — match against label or description;\n      # applied in the outer query so it can reference the fetched label/alias variables\n      FILTER(\n        REGEX(STR(?qlue_ls_label), "^{{ search_term }}", "i")\n        || REGEX(STR(?qlue_ls_alias), "^{{ search_term }}", "i")\n      )\n      {% endif %}\n    }',
                help_text="The query for <em>context-sensitive</em> values autocompletion",
                verbose_name="Values completion (context sensitive)",
            ),
        ),
    ]
