# Generated by Django 5.2.7 on 2026-03-22 20:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_comparegroup'),
        ('api', '0011_alter_sparqlendpointconfiguration_hover_and_more'),
    ]

    operations = [
    ]
