PREFIX wd: <http://www.wikidata.org/entity/>
PREFIX wdt: <http://www.wikidata.org/prop/direct/>
PREFIX p: <http://www.wikidata.org/prop/>
PREFIX psn: <http://www.wikidata.org/prop/statement/value-normalized/>
PREFIX wikibase: <http://wikiba.se/ontology#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX schema: <http://schema.org/>
SELECT ?movie ?movieLabel ?narrative_location ?narrative_locationLabel ?sitelinks ?coordinates WHERE {
  ?movie wdt:P840 ?narrative_location ;
  wdt:P31 wd:Q11424 .
  ?narrative_location wdt:P625 ?coordinates .
  ?movie ^schema:about/wikibase:sitelinks ?sitelinks .
  ?movie rdfs:label ?movieLabel .
  ?narrative_location rdfs:label ?narrative_locationLabel .
  FILTER (LANG(?movieLabel) = "en") .
  FILTER (LANG(?narrative_locationLabel) = "en") .
}
ORDER BY DESC(?sitelinks)