PREFIX wd: <http://www.wikidata.org/entity/>
PREFIX wdt: <http://www.wikidata.org/prop/direct/>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
SELECT ?name WHERE {
  ?country wdt:P31 wd:Q6256 .
  ?country rdfs:label ?name .
  FILTER (lang(?name) = "de")
}
ORDER BY ASC(?name)