PREFIX wikibase: <http://wikiba.se/ontology#>
PREFIX psn: <http://www.wikidata.org/prop/statement/value-normalized/>
PREFIX wd: <http://www.wikidata.org/entity/>
PREFIX wdt: <http://www.wikidata.org/prop/direct/>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX p: <http://www.wikidata.org/prop/>
SELECT DISTINCT ?country ?country_name ?mountain ?mountain_name ?max_height WHERE {
  { SELECT ?country (MAX(?height) AS ?max_height) WHERE {
    ?mountain wdt:P31/wdt:P279* wd:Q8502 .
    ?mountain p:P2044/psn:P2044/wikibase:quantityAmount ?height .
    ?mountain wdt:P17 ?country .
  } GROUP BY ?country }
  ?mountain wdt:P31/wdt:P279* wd:Q8502 .
  ?mountain p:P2044/psn:P2044/wikibase:quantityAmount ?max_height .
  ?mountain wdt:P17 ?country .
  ?mountain rdfs:label ?mountain_name FILTER (LANG(?mountain_name) = "en")
  ?country rdfs:label ?country_name FILTER (LANG(?country_name) = "en")
}
ORDER BY DESC(?max_height)