[project]
name = "qlue-ui-backend"
version = "0.6.0"
description = "Backend API for Qlue-UI"
requires-python = "==3.14.7"
dependencies = [
    "fastapi[standard]==0.141.1",
    "uvicorn[standard]==0.52.4",
    "pydantic==2.13.5",
    "pyyaml==6.0.3",
    "watchdog==6.0.0",
]

[tool.setuptools.package-data]
api = ["banner.txt", "presets/*.yaml", "defaults/config.yaml", "defaults/examples/*/*.rq"]
