PREFIX wd: <http://www.wikidata.org/entity/>
PREFIX wdt: <http://www.wikidata.org/prop/direct/>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
SELECT DISTINCT ?astronautLabel ?time_in_space WHERE {
  ?astronaut wdt:P106 wd:Q11631 .
  ?astronaut wdt:P2873 ?time_in_space .
  ?astronaut rdfs:label ?astronautLabel .
  FILTER (LANG(?astronautLabel) = "en") .
}
ORDER BY DESC(?time_in_space)