PREFIX wikibase: <http://wikiba.se/ontology#>
PREFIX wd: <http://www.wikidata.org/entity/>
PREFIX wdt: <http://www.wikidata.org/prop/direct/>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX schema: <http://schema.org/>
SELECT DISTINCT ?astronaut_name ?sitelinks WHERE {
  ?astronaut wdt:P106 wd:Q11631 .
  ?astronaut rdfs:label ?astronaut_name .
  ?astronaut_node schema:about ?astronaut .
  ?astronaut_node wikibase:sitelinks ?sitelinks .
  FILTER (LANG(?astronaut_name) = "en")
}
ORDER BY DESC(?sitelinks)