PREFIX osmrel: <https://www.openstreetmap.org/relation/>
PREFIX geo: <http://www.opengis.net/ont/geosparql#>
PREFIX osm: <https://www.openstreetmap.org/>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX osmkey: <https://www.openstreetmap.org/wiki/Key:>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
SELECT ?region ?name ?geometry WHERE {
  { ?region osmkey:boundary "administrative" . ?region osmkey:admin_level "6"^^xsd:int . ?region rdf:type osm:relation }
  UNION
  { VALUES ?region { osmrel:62782 osmrel:62422 } }
  ?region osmkey:name ?name .
  ?region geo:hasGeometry ?geometry .
}