PREFIX geo: <http://www.opengis.net/ont/geosparql#>
PREFIX osmkey: <https://www.openstreetmap.org/wiki/Key:>
SELECT ?osm_id ?geometry WHERE {
  ?osm_id osmkey:amenity "post_box" .
  ?osm_id geo:hasGeometry/geo:asWKT ?geometry
}