PREFIX osm: <https://www.openstreetmap.org/>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX osmt: <https://www.openstreetmap.org/wiki/Key:>
PREFIX geo: <http://www.opengis.net/ont/geosparql#>
PREFIX osmway: <https://www.openstreetmap.org/way/>
SELECT DISTINCT ?node ?coordinates ?name WHERE {
  ?way osmt:highway ?highway .
  ?way rdf:type osm:way .
  ?way osmway:node/osmway:node ?node .
  ?node geo:hasGeometry ?coordinates .
  OPTIONAL { ?node osmt:name ?name }
}