PREFIX osm2rdf: <https://osm2rdf.cs.uni-freiburg.de/rdf#>
PREFIX ogc: <http://www.opengis.net/rdf#>
PREFIX osmrel: <https://www.openstreetmap.org/relation/>
PREFIX geo: <http://www.opengis.net/ont/geosparql#>
PREFIX osm: <https://www.openstreetmap.org/>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX osmkey: <https://www.openstreetmap.org/wiki/Key:>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX wd: <http://www.wikidata.org/entity/>
PREFIX wdt: <http://www.wikidata.org/prop/direct/>
PREFIX p: <http://www.wikidata.org/prop/>
PREFIX ps: <http://www.wikidata.org/prop/statement/>
SELECT DISTINCT ?region ?name ?geometry WHERE {
  ?country osm:wikidata ?country_wd .
  ?country osm2rdf:contains_area+ ?region .
  ?region osmkey:boundary "administrative" .
  ?region osmkey:name ?name .
  ?region geo:hasGeometry ?geometry .
  ?region rdf:type osm:relation .
  ?region osmkey:admin_level "4" .
  SERVICE <https://qlever.cs.uni-freiburg.de/api/wikidata> {
	?country_wd p:P37/ps:P37/@en@rdfs:label "English"@en
  }
}