SELECT ?p ?count (100 * ?count / ?count_all AS ?percent) WHERE {
  { SELECT ?p (COUNT(?p) AS ?count) WHERE { ?s ?p ?o } GROUP BY ?p }
  { SELECT (COUNT(?s) AS ?count_all) WHERE { ?s ?p ?o } }
}
ORDER BY DESC(?count)